### ISSUE TITLE
Ability to specify fields to return by nested keys

### ISSUE THREAD

**Issue by abovedave** [dadi/api#397] opened 2018-03-21 15:46 UTC
Currently, I'm unable to filter specific fields of a Reference object in a Web datasource.

E.g., The query would be `fields={"title": 1, "author.name": 1}`

```json
{
  "datasource": {
    "key": "articles",
    "source": {
      "endpoint": "1.0/publisher/articles"
    },
    "paginate": 1,
    "count": 1,
    "fields": {
      "title": 1,
      "author.name": 1
    }
  }
}
```

This returns the title field, but a blank author array (author is a reference field)

```
{
  "results": [
    {
      "_composed": {
        "author": []
      },
      "_id": "5a946688dc5fc266552d2f25",
      "author": [],
      "title": "Why you should open source your website"
    },
    {
      "_composed": {
        "author": []
      },
      "_id": "5a9684827abb4273bcce608d",
      "author": [],
      "title": "Forming an orderly queue"
    }
}
```

**Comment by eduardoboucas** [comment] 2018-03-27 15:17
Isn't this a duplicate of #329?

**Comment by jimlambie** [comment] 2018-03-27 15:18
@eduardoboucas yes it is!

**Comment by eduardoboucas** [comment] 2018-03-27 15:19
I'll close and fix. Then we'll all be happy. 👨‍👧‍👦

**Closed by eduardoboucas** 2018-03-27 15:19 UTC
Labels: type: bug
